### ISSUE TITLE
Per class recall

### ISSUE THREAD

**Issue by aorad** [dbolya/tide#11]
Do you plan on supporting per class metrics?

**Comment by dbolya** [comment]
Support already exists, but is buried a little deeper in the code.

However, recall will not be supported. Just use COCOEval for that.

**Comment by kdk2612** [comment]
How can we access the per class metric? @dbolya

**Comment by dbolya** [comment]
@kdk2612 
```py
run = tide.evaluate(gt, results)

for class_id, ap_data in run.ap_data.objs.items():
    print('{:10s}: {:.2f}'.format(str(class_id), ap_data.get_ap()))
```

This will print out the AP for each class ID individually for the given run.

**Comment by kdk2612** [comment]
I am getting different results using this vs the pyCoco tools. Is there a reason for that?

**Comment by dbolya** [comment]
The code I showed gives you the per-class mAP @ 50. the COCO evaluation toolkit probably gives you @ 50:95.

**Comment by kdk2612** [comment]
No not using the code, using the entire project.

**Comment by kdk2612** [comment]
the mAP values for the evaluation are different

**Comment by dbolya** [comment]
Can you create a new issue for this with what TIDE outputs vs. what pycocotools outputs?
