### ISSUE TITLE
What does 'suppress'  in the paper mean?

### ISSUE THREAD

**Issue by LiewFeng** [dbolya/tide#30]
Hi, @dbolya .  The oracle will suppress some detection when fixing an error. Does  'suppress' mean deleting the detection or treating the detection as a false positive?  Thanks.

**Comment by dbolya** [comment]
Deleting the detection.

This happens here:
https://github.com/dbolya/tide/blob/49a5d2a4aeb56795e93a3ed7cc7e6d25757bb4c1/tidecv/errors/error.py#L87-L123
